// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8rApi3UFwdQqQadDepPbazAW9Mqx50I',
    appId: '1:1005179153071:web:6226cf83ef6d123739825a',
    messagingSenderId: '1005179153071',
    projectId: 'flutter-firebase-a72d0',
    authDomain: 'flutter-firebase-a72d0.firebaseapp.com',
    storageBucket: 'flutter-firebase-a72d0.firebasestorage.app',
    measurementId: 'G-KHT988GQX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIG8x2j_bQ7NEEs8mafTAOy60AjhMhxGA',
    appId: '1:1005179153071:android:9bfbc6e9067af6a739825a',
    messagingSenderId: '1005179153071',
    projectId: 'flutter-firebase-a72d0',
    storageBucket: 'flutter-firebase-a72d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmkE2r5G-3S_v4yjhzvwhXEJ7fKBZKtqI',
    appId: '1:1005179153071:ios:8ac0f3417caa504239825a',
    messagingSenderId: '1005179153071',
    projectId: 'flutter-firebase-a72d0',
    storageBucket: 'flutter-firebase-a72d0.firebasestorage.app',
    iosClientId: '1005179153071-fllnq14fcnrp9n1l2a6vo22rs7d25psd.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmkE2r5G-3S_v4yjhzvwhXEJ7fKBZKtqI',
    appId: '1:1005179153071:ios:8ac0f3417caa504239825a',
    messagingSenderId: '1005179153071',
    projectId: 'flutter-firebase-a72d0',
    storageBucket: 'flutter-firebase-a72d0.firebasestorage.app',
    iosClientId: '1005179153071-fllnq14fcnrp9n1l2a6vo22rs7d25psd.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb8rApi3UFwdQqQadDepPbazAW9Mqx50I',
    appId: '1:1005179153071:web:db76f0e43c79939539825a',
    messagingSenderId: '1005179153071',
    projectId: 'flutter-firebase-a72d0',
    authDomain: 'flutter-firebase-a72d0.firebaseapp.com',
    storageBucket: 'flutter-firebase-a72d0.firebasestorage.app',
    measurementId: 'G-4KMENSN1Z7',
  );
}
